#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
# Copyright (C) 2026 @Mige99 
#
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Client Status Monitor && Management
LUCI_DEPENDS:=+clientstatus +luci-compat
LUCI_PKGARCH:=all

PKG_VERSION:=1.0.9
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
