
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Client Status Monitor && Management
LUCI_DEPENDS:=+clientstatus
LUCI_PKGARCH:=all

PKG_VERSION:=1.0.8
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
